service: back-tcg

variablesResolutionMode: 20210326

frameworkVersion: "2"

plugins:
  - serverless-webpack # must be the first of the list
  - serverless-dynamodb-local
  - serverless-offline # must be the last of the list

provider:
  name: aws
  runtime: nodejs16.x
  environment: 
    gamesTableName: Games
    playersTableName: Players

functions:
  create:
    handler: ./src/apps/games/handlers/createGame.main
    events:
    - http:
        path: games
        method: post

resources:
  Resources:
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.gamesTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PlayersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.playersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: _gameId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
        - IndexName: gameIndex
          KeySchema:
            - AttributeName: _gameId
              KeyType: HASH
          Projection:
            ProjectionType: ALL


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn # or npm
    includeModules: true

  dynamodb:
    stages:
      - local
    start:
      docker: true
      image: dynamodb-local
      port: 8000
      inMemory: true
      noStart: true
      migrate: true
      seed: true
    seed:
      default:
        sources:
        - table: ${self:provider.environment.gamesTableName}
          sources: [./seeds/games.json]