service: back-tcg

variablesResolutionMode: 20210326

frameworkVersion: "2"

plugins:
  - serverless-webpack # must be the first of the list
  - serverless-dynamodb-local
  - serverless-offline # must be the last of the list

provider:
  name: aws
  runtime: nodejs16.x

functions:
  create:
    handler: ./src/handlers/createEmployee.main
    events:
    - http:
        path: employees
        method: post

resources:
  GameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Games
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: hello
          KeySchema: 
          Projection:
            ProjectionType: ALL
 

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: yarn # or npm
    includeModules: true

  dynamodb:
    stages:
      - local
    start:
      docker: true
      image: dynamodb-local
      port: ${param-dynamodbPort}
      inMemory: true
      noStart: true
      migrate: true